word = str(input("Enter a word atleast 5 characters long: "))
print(word[2])
print(word[-2])
print(word[0:5])
print(word[:-2])
print(word[::2])
print(word[1::2])
print(word[::-1])
print(word[::-2])
print(len(word))
